_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "ours.pth"
  TRANSFORMER:
    VOC_SIZE: 96
    NUM_POINTS: 25
    LOSS:
        CATMULL_SAMPLE_POINTS: 25
        CATMULL_CLASS_WEIGHT: 1.0
        CATMULL_COORD_WEIGHT: 0.5
        POINT_CLASS_WEIGHT: 1.0
        POINT_COORD_WEIGHT: 0.5
        POINT_TEXT_WEIGHT: 0.25
        BOUNDARY_WEIGHT: 0.25
  
DATASETS:
  TRAIN: ("IPM2025_train_96voc",)
  TEST: ("IPM2025_test_96voc",)

INPUT:
  ROTATE: False
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 4000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/IPM2025/finetune_maxlen25_96voc"
